### PR TITLE
improve documentation readability

### PR DESCRIPTION
**Pull request by eafyounian**
Minor modifications to improve documentation readability.

### CODE REVIEW

**Comment by eafyounian** [comment]
I made some changes to the `quick_start_API.ipynb` to improve the readability. I wonder whether the `quick_start_API.html` file in the documentation should be built separately for changes to show up in the documentation or will it happen automatically?

**Comment by zhqu1148980644** [comment]
you can check contributions.md in the root path of this repo

**Comment by zhqu1148980644** [comment]
Thanks!

**Comment by zhqu1148980644** [comment]
hi, it seems that the doc is not updated, have you run the `build doc` command listed in `CONTRIBUTIONS.md`?

**Comment by eafyounian** [comment]
Thank you! :) I made the modifications on a Windows machine and I am unable to create the environment (it fails e.g. because of samtools, ...). Is it possible for you to build the doc?

**Comment by zhqu1148980644** [comment]
Sure, I will build it later and try to automate this build step.

**Comment by eafyounian** [comment]
Great! Thanks! :)

**Pull request merged**
