### PR TITLE
Allow jointview with no side tracks

### PR DESCRIPTION
**Pull request by zhqu1148980644**
Fix error when input one sidetrack for jointview, and allow for no side track

### CODE REVIEW

**Comment by Nanguage** [comment]
Why need this? I think when less than two sub-frame, the normal frame is the better choice.

**Comment by zhqu1148980644** [comment]
you are right, it makes sense. I'll close this.

**Comment by zhqu1148980644** [comment]
Maybe the assert error msg can be more precise.

**Comment by Nanguage** [comment]
Yes, should promot user to use the normal frame here.

**Comment by Nanguage** [comment]
Wait! I realized that I was wrong, it's different to normal frame, it can visualize the trans interaction, the normal frame can not.

**Comment by zhqu1148980644** [comment]
I didn't thought of it either, The CLI mode can also use joint view when receiving a single hicmat track with 2d genome range.

**Pull request merged**
